### ISSUE TITLE
Lembrar de levar a garrafinha

### ISSUE THREAD

**Issue by Eduardolimr** [Lucas362/toptop#4]
Eu, como usuário, quero não esquecer de levar a garrafinha para a faculdade.

# Critérios de aceitação

- [ ] Pensar em levar a garrafinha.

**Comment by Lucas362** [comment]
Acredito que a equipe não demonstra habilidade suficiente para a realização da presente tarefa, peço encarecidamente pela refatoração dos critérios de aceitação referentes a mesma.

**Comment by Eduardolimr** [comment]
Atualizei os critérios de aceitação devido pedidos da equipa.
